export function getMenu() {
  return [
    {
      id: 1,
      nombre: "Banavara",
      descripcion:
        "Deliciosa crepe rellena con Nutella auténtica, plátano fresco y fresas, decorada con azúcar glass y crema batida.",
      precio: 3500,
      imagenes: ["/images/menuImages/crepas/Banavara.webp"],
      ingredientes: ["Nutella", "Plátano", "Fresas"],
      disponible: true,
      categoria: "Bebidas Frías",
    },
    {
      id: 2,
      nombre: "BerryVara",
      descripcion:
        "Deliciosa crepe rellena con Nutella auténtica, plátano fresco y fresas, decorada con azúcar glass y crema batida.",
      precio: 3500,
      imagenes: ["/images/menuImages/crepas/Berryvara.webp"],
      ingredientes: ["Nutella", "Plátano", "Fresas"],
      disponible: true,
      categoria: "Bebidas Frías",
    },
    {
      id: 3,
      nombre: "CafeCrepiVara",
      descripcion:
        "Deliciosa crepe rellena con Nutella auténtica, plátano fresco y fresas, decorada con azúcar glass y crema batida.",
      precio: 3500,
      imagenes: ["/images/menuImages/crepas/Cafecrepivara.webp"],
      ingredientes: ["Nutella", "Plátano", "Fresas"],
      disponible: false,
      categoria: "Bebidas Calientes", // ajusta según corresponda
    },
    {
      id: 4,
      nombre: "CafeVara",
      descripcion:
        "Deliciosa crepe rellena con Nutella auténtica, plátano fresco y fresas, decorada con azúcar glass y crema batida.",
      precio: 3500,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["Nutella", "Plátano", "Fresas"],
      disponible: true,
      categoria: "Bebidas Frías", // ajusta según corresponda
    },
    {
      id: 5,
      nombre: "CAPIBERRY",
      descripcion:
        "Deliciosa crepe rellena con Nutella auténtica, plátano fresco y fresas, decorada con azúcar glass y crema batida.",
      precio: 1900,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["2 frutas", "Jarabe", "Topping"],
      disponible: true,
      categoria: "Crepas",
    },
    {
      id: 6,
      nombre: "CREPA SIN FRUTA",
      descripcion:
        "Deliciosa crepe rellena con Nutella auténtica, plátano fresco y fresas, decorada con azúcar glass y crema batida.",
      precio: 2400,
      imagenes: ["/images/menuImages/crepas/CrepaSinFruta.webp", "/images/menuImages/crepas/CrepaSinFruta2.webp"],
      ingredientes: ["Helado", "Topping", "Jarabe"],
      disponible: true,
      categoria: "Crepas",
    },
    {
      id: 7,
      nombre: "TROPICALVARA",
      descripcion:
        "Deliciosa crepe rellena con Nutella auténtica, plátano fresco y fresas, decorada con azúcar glass y crema batida.",
      precio: 2900,
      imagenes: ["/images/menuImages/crepas/TropicalVara1.webp"],
      ingredientes: ["Banano", "Fresas", "Helado", "Jarabe"],
      disponible: true,
      categoria: "Crepas",
    },
    {
      id: 8,
      nombre: "CAPIDULZURA",
      descripcion:
        "Deliciosa crepe rellena con Nutella auténtica, plátano fresco y fresas, decorada con azúcar glass y crema batida.",
      precio: 3400,
      imagenes: ["/images/menuImages/crepas/CrepiDulzura1.webp", "/images/menuImages/crepas/CrepiDulzura2.webp"],
      ingredientes: ["Melocotón", "Fresa", "Helado", "Nutella"],
      disponible: true,
      categoria: "Crepas",
    },
    {
      id: 9,
      nombre: "CAPIOREO",
      descripcion:
        "Deliciosa crepe rellena con Nutella auténtica, plátano fresco y fresas, decorada con azúcar glass y crema batida.",
      precio: 4500,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["2 frutas", "Helado", "Oreo", "Jarabe", "Toppin"],
      disponible: true,
      categoria: "Crepas",
    },
    {
      id: 10,
      nombre: "LA CREPIVARA",
      descripcion:
        "Deliciosa crepe rellena con Nutella auténtica, plátano fresco y fresas, decorada con azúcar glass y crema batida.",
      precio: 6400,
      imagenes: ["/images/menuImages/crepas/CrepiVara1.webp", "/images/menuImages/crepas/CrepiVara2.webp"],
      ingredientes: [
        "3 frutas",
        "2 Helados",
        "Toppin",
        "Crema Chantylly",
        "Nutella",
      ],
      disponible: true,
      categoria: "Crepas",
    },
    {
      id: 11,
      nombre: "Batido 1",
      descripcion: "Batido Natural en Agua",
      precio: 1450,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: [
        "Cas",
        "Mora",
        "Piña",
        "Sandía",
        "Guanabana",
        "fresa",
        "mora",
      ],
      disponible: true,
      categoria: "Bebidas Frías",
    },
    {
      id: 12,
      nombre: "Batido 2",
      descripcion: "Batido en leche",
      precio: 1950,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: [
        "Mora",
        "Piña",
        "Guanabana",
        "Banano",
        "Papaya",
        "fresa",
        "melon",
      ],
      disponible: true,
      categoria: "Bebidas Frías",
    },
    {
      id: 13,
      nombre: "CHURCHILL",
      descripcion: " Bebida refrescante",
      precio: 3450,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: [""],
      disponible: true,
      categoria: "Bebidas Frías",
    },
    {
      id: 14,
      nombre: "CAFÉ FRIO",
      descripcion: "Cafe Frio",
      precio: 2200,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: [""],
      disponible: true,
      categoria: "Bebidas Frías",
    },
    {
      id: 15,
      nombre: "MANGONADAS",
      descripcion: "Mango",
      precio: 2400,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["Mango", "Tajin", "Chamoy", "Gomitas"],
      disponible: true,
      categoria: "Bebidas Frías",
    },
    {
      id: 16,
      nombre: "TÉ",
      descripcion: "Te caliente",
      precio: 800,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: [""],
      disponible: true,
      categoria: "Bebidas Calientes",
    },
    {
      id: 17,
      nombre: "CAFÉ NEGRO",
      descripcion: "Cafe caliente",
      precio: 800,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: [""],
      disponible: true,
      categoria: "Bebidas Calientes",
    },
    {
      id: 18,
      nombre: "CAFÉ CON LECHE",
      descripcion: "Cafe caliente",
      precio: 900,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: [""],
      disponible: true,
      categoria: "Bebidas Calientes",
    },
    {
      id: 19,
      nombre: "CHOCOLATE",
      descripcion: "Chocolate caliente",
      precio: 900,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: [""],
      disponible: true,
      categoria: "Bebidas Calientes",
    },
    {
      id: 35,
      nombre: "CONO SENCILLO",
      descripcion: "Cono simple con una porcion de helado",
      precio: 600,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["1 helado"],
      disponible: true,
      categoria: "Helados",
    },
    {
      id: 36,
      nombre: "CONO DOBLE",
      descripcion: "Cono con dos porciones de helado",
      precio: 900,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["2 helados"],
      disponible: true,
      categoria: "Helados",
    },
    {
      id: 20,
      nombre: "HELADO CON GELATINA",
      descripcion: "Helado con gelatina",
      precio: 1900,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["1 helado", "gelatina"],
      disponible: true,
      categoria: "Helados",
    },
    {
      id: 21,
      nombre: "ENSALADA DE FRUTAS",
      descripcion: "Una ensalada refrescante con helado",
      precio: 2900,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["3 frutas", "1 Helado", "1 Topping"],
      disponible: true,
      categoria: "Helados",
    },
    {
      id: 22,
      nombre: "CANASTA CON HELADO",
      descripcion: "Una canasta de helado deleciosa",
      precio: 2400,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: [""],
      disponible: true,
      categoria: "Helados",
    },
    {
      id: 23,
      nombre: "CHOCO BANANO ESPECIAL",
      descripcion: "Delicioso choco banano",
      precio: 1900,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["Leche Pinito", "1 Jarabe", "1 Topping"],
      disponible: true,
      categoria: "Helados",
    },
    {
      id: 24,
      nombre: "BANANA SPLIT",
      descripcion: "Banano con helado delicioso para dias calientes",
      precio: 3495,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["Banano", "Helado", "1 Topping", "1 Jarabe", "Chantilly"],
      disponible: true,
      categoria: "Helados",
    },
    {
      id: 25,
      nombre: "GRANIZADO SENCILLO",
      descripcion: "Granizado sencillo",
      precio: 995,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["1 Leche", "Sirope"],
      disponible: true,
      categoria: "Granizados",
    },
    {
      id: 26,
      nombre: "GRANIZADO ESPECIAL",
      descripcion: "Granizado ESPECIAL",
      precio: 1795,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["2 Leches", "Sirope", "1 topping", "1 jarabe"],
      disponible: true,
      categoria: "Granizados",
    },
    {
      id: 27,
      nombre: "FRESA PEQUEÑA",
      descripcion: "Fresa Pequeña",
      precio: 1900,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["1 topping", "1 Jarabe"],
      disponible: true,
      categoria: "Fresas",
    },
    {
      id: 28,
      nombre: "FRESA GRANDE",
      descripcion: "Fresa Grande",
      precio: 2900,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["2 Topping", "2 Jarabe"],
      disponible: true,
      categoria: "Fresas",
    },
    {
      id: 29,
      nombre: "WAFFLE Con Helado",
      descripcion: "Waffle Con Helado",
      precio: 4500,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["2 Frutas", "1 Topping", "1 Jarabe", "2 Helados"],
      disponible: true,
      categoria: "Fresas",
    },
    {
      id: 30,
      nombre: "WAFFLE SENCILLO",
      descripcion: "Waffle sencillo",
      precio: 3400,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: ["2 frutas","1 Topping", "1 Jarabe"],
      disponible: true,
      categoria: "Fresas",
    },
    {
      id: 31,
      nombre: "TOPPING",
      descripcion: "Topping",
      precio: 350,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: [""],
      disponible: true,
      categoria: "Extras",
    },
    {
      id: 32,
      nombre: "JARABE",
      descripcion: "Jarabe",
      precio: 350,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: [""],
      disponible: true,
      categoria: "Extras",
    },
    {
      id: 33,
      nombre: "Helado",
      descripcion: "1 PORCION DE HELADO",
      precio: 500,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: [""],
      disponible: true,
      categoria: "Extras",
    },
    {
      id: 34,
      nombre: "NUTELLA",
      descripcion: "1 PORCION DE HELADO",
      precio: 500,
      imagenes: ["/images/menuImages/crepas/Cafevara.webp"],
      ingredientes: [""],
      disponible: true,
      categoria: "Extras",
    },
  ];
}


//Id de las recomendadas de 1000 para arriba
export function getRecommended(){

   return [
    getMenu().find(item => item.id === 10),
    getMenu().find(item => item.id === 8),
    getMenu().find(item => item.id === 29),
    getMenu().find(item => item.id === 12),
  ]
}
